feat: revert 복원
cholog-project/supp pull request #36
Opened 2024-10-13 05:12 UTC by boyekim

2024-10-13 08:06 UTC, gogo1414 requested changes
고생했어요~~~
수정할 사항 몇가지 존재해서 확인 부탁드려요!!

2024-10-13 08:06 UTC, gogo1414 commented on src/main/java/cholog/supp/api/post/controller/PostController.java
> +    }
일부러 두 API "/posts" 로 겹치게 둔건가요??

2024-10-13 08:06 UTC, gogo1414 commented on src/main/java/cholog/supp/api/post/controller/PostController.java
> +        @RequestBody PostsRequest postsRequest) {
여기도 `@RequestBody` 어노테이션으로 되어있네 수정 부탁드려요!

2024-10-13 08:06 UTC, gogo1414 commented on src/main/java/cholog/supp/api/member/dto/response/EmailValidationResponse.java
단순 의견이긴 한데 나중에 로그 보기 쉽게 표현하려면 `String message` 같은 필드도 있으면 좋을거 같긴 한데? 어떤가요??

2024-10-13 08:06 UTC, gogo1414 commented on src/main/java/cholog/supp/api/member/service/MemberService.java
> +    }
해당 이메일 검증을 같은 MemberService에 존재하는 다른 서비스 로직인 `signUp`에 사용해도 괜찮을거 같은데 어떻게 생각하나요??

2024-10-13 08:06 UTC, gogo1414 commented on src/main/java/cholog/supp/api/post/controller/PostController.java
> +    }
**HTTP method** 로 분리 가능해서 그런걸까요??

2024-10-13 08:06 UTC, gogo1414 commented on src/main/java/cholog/supp/api/study/controller/StudyGroupController.java
>          var response = studyGroupService.getGroup(member);
`var`를 갑자기 사용한 이유가 있을까요????

2024-10-13 08:06 UTC, gogo1414 commented on src/main/java/cholog/supp/db/comment/Comment.java
>          this.post = post;
줄 공백이 한 줄 더들어갔어요!!
```suggestion
    @CreatedDate
    @Column(name = "created_date", nullable = false)
    private LocalDateTime createdDate;

    @LastModifiedDate
    @Column(name = "modified_date")
    private LocalDateTime modifiedDate;

    public Comment(Member member, Post post, String content) {
        this.member = member;
        this.post = post;
```

2024-10-13 08:06 UTC, gogo1414 commented on src/main/java/cholog/supp/db/comment/Comment.java
생성시간, 수정시간이 들어갔네요👍👍👍

2024-10-13 08:55 UTC, boyekim commented on src/main/java/cholog/supp/api/post/controller/PostController.java
> +    }
하나는 post, 다른 하나는 posts입니다~!~!
[url 의견교환 링크](https://github.com/cholog-project/supp/pull/28) 에 태현오빠랑 논의한 것이 있사와요
단건이랑 url링크 상 이름을 분리해야 다른사람이 쉽게 인지할 수 있을 것 같았어!!
안헷갈리게 단건이랑 다건이랑 클래스를 분리해도 좋을 것 같다는 생각이 드네

2024-10-13 08:56 UTC, boyekim commented on src/main/java/cholog/supp/api/post/controller/PostController.java
> +        @RequestBody PostsRequest postsRequest) {
왁 그러네!! `@RequestParam`으로 수정할게~~~

2024-10-13 08:56 UTC, boyekim commented on src/main/java/cholog/supp/api/member/dto/response/EmailValidationResponse.java
처음에 도입하려다가 뺀 것이긴 해!!
일주일만에 개발해야하니 message enum 관리에 드는 비용이 없는게 좋을 것 같더라구...

2024-10-13 09:02 UTC, boyekim commented on src/main/java/cholog/supp/api/member/service/MemberService.java
> +    }
처음에 그렇게 구상하고 그 안에 로직을 넣었었는데, 서비스 흐름도 상 따로 api를 빼는 것이 낫다고 판단되었어!!!
처음에는 signUp에서 회원가입 버튼을 누르면 그 때 이메일 인증을 하고, 이미 존재하는 이메일이라면 그 때 존재하는 이메일이라고 말해주려했는데
현재 논의된 서비스는 이메일 입력 칸 옆에 '중복확인' 버튼을 두고 그 중복확인 버튼을 눌렀을 때 존재하는지 확인하게 만들기로 했어
혹시 회원가입버튼을 눌렀을 때에도 한번 더 확인하자고 의견을 주는 걸까?
프론트 쪽에서 중복확인 버튼에서 
1. 안눌렀을 경우 
2. 눌렀어도 true값(db에 해당 이메일이 존재)인 경우

회원가입 버튼을 못누르게 처리 못하나...?!?!그것도 백엔드의 영역일까??

2024-10-13 09:02 UTC, boyekim commented on src/main/java/cholog/supp/api/study/controller/StudyGroupController.java
>          var response = studyGroupService.getGroup(member);
고쳐두겟습니댜

2024-10-13 09:02 UTC, boyekim commented on src/main/java/cholog/supp/db/comment/Comment.java
>          this.post = post;
허걱스 감사해여

2024-10-13 09:24 UTC, gogo1414 commented on src/main/java/cholog/supp/api/post/controller/PostController.java
> +    }
좋네요~~😊

2024-10-13 09:25 UTC, gogo1414 commented on src/main/java/cholog/supp/api/member/dto/response/EmailValidationResponse.java
추후에 기회가 있으면 그때 적용하자~~😁

2024-10-13 09:28 UTC, gogo1414 commented on src/main/java/cholog/supp/api/member/service/MemberService.java
> +    }
**중복확인 버튼 클릭**으로 중복확인을 진행하니 API가 별도로 분리되는구나

서비스가 **중복 확인**으로 진행되는거라면 
### 회원 가입 클릭 시 
1. 중복 확인 버튼을 눌렀는지 체크하고 누르지 않았으면 체크 문구를 띄운다. 
2. 중복 확인 클릭 시 아이디 변경이 존재할 경우 다시 중복 확인을 클릭하라는 문구를 띄운다.
3. 중복 확인 클릭 시 아이디 변경 불가능하게
이렇게 프론트엔드에서 진행될거 같아

2024-10-13 09:29 UTC, gogo1414 approved these changes

2024-10-14 08:28 UTC, Choi-JJunho approved these changes

2024-10-14 08:29 UTC, merged