feat: 나머지 API 개발
cholog-project/supp pull request #37
Opened 2024-10-13 12:58 UTC by boyekim

시간관계상 남은 api 개발 완료해서 한번에 올려요ㅜ
보기 힘들텐데 미앙해요

2024-10-13 13:52 UTC, whxogus215 reviewed
주말동안 계속 작업하느라 고생많았어! 꼼꼼히 코드리뷰 해줘야 했는데 못해줘서 미안해 😢

2024-10-13 13:52 UTC, whxogus215 commented on src/main/java/cholog/supp/common/validation/Validation.java
> +
공백 한 줄이 추가된 것 같아!

2024-10-13 13:52 UTC, whxogus215 commented on src/main/java/cholog/supp/api/study/controller/StudyGroupController.java
>          var response = studyGroupService.getGroup(member);
이 코드에만 `var` 타입이 쓰인 것 같은데 `var`를 사용한 의도가 무엇인지 궁금해

2024-10-13 13:52 UTC, whxogus215 commented on src/main/java/cholog/supp/api/post/dto/response/EachComment.java
> +
공백 한 줄 추가되어 있어!

2024-10-13 13:52 UTC, whxogus215 commented on src/main/java/cholog/supp/api/post/dto/ModifyPost.java
`ModifyPost`와 `ModifyPostRequest`가 서로 어떠한 상황에서 쓰이는지 알 수 있을까?
둘 다 글을 수정할 때 사용되는 DTO인 것 같은데 어떠한 차이점이 있는지 궁금해.

2024-10-13 14:51 UTC, boyekim commented on src/main/java/cholog/supp/api/study/controller/StudyGroupController.java
>          var response = studyGroupService.getGroup(member);
요것은 이전 pr에서 수정을 했어!! 아직 머지가 안되어서 여기도 반영이 안되어있어ㅜ

2024-10-13 14:59 UTC, boyekim commented on src/main/java/cholog/supp/api/post/dto/ModifyPost.java
`ModifyPostRequest`는 수정 요청을 받아오는 객체야!
그리고 `ModifyPost` 는 엔티티 수정을 할 때에 사용할 dto라서 분리했어. Post 엔티티의 title과 description 값을 수정할 때 저 객체에 담아서 엔티티에 전달해!
```
public void modifyPost(ModifyPost modifyPost) {
        this.title = modifyPost.title();
        this.description = modifyPost.description();
}
```
역할이 확연히 다른 것 같아서 분리했어!! post가 엔티티명이니까 `ModifyPost` 클래스 명이 명확하다구 생각했었거든? 좀 헷갈리려나??

2024-10-13 15:05 UTC, whxogus215 commented on src/main/java/cholog/supp/api/post/dto/ModifyPost.java
아 코드보고 이해했어! 내가 제대로 코드를 못보고 물어봤던 것 같네 🥲

2024-10-13 22:14 UTC, Choi-JJunho requested changes
주말동안 개발 진짜많이했네 ㄷㄷㄷ
고생많았어!
코멘트 몇개 확인부탁할게

2024-10-13 22:14 UTC, Choi-JJunho commented on src/main/java/cholog/supp/api/post/controller/PostController.java
> +    @PostMapping("/post")
나는 개인적으류 API Path는 복수형으로 두는걸 선호하는데 단수, 복수를 혼합한 이유가 있을까?

https://blog.pumpkin-raccoon.com/115

2024-10-13 22:14 UTC, Choi-JJunho commented on src/main/java/cholog/supp/api/post/dto/request/PostsRequest.java
> +}
여기 EOL(End Of Line) 놓쳤다!
![image](https://github.com/user-attachments/assets/e46042fe-3a4d-4d2d-b9d2-0fecf0c26525)

2024-10-13 22:14 UTC, Choi-JJunho commented on src/main/java/cholog/supp/db/post/Post.java
> +    private LocalDateTime modifiedDate;
위에있는 EntityListener랑 이 생성, 수정일자 정보가 중복되니까 abstract class로 공통화시켜볼수 있을거같아

2024-10-14 01:58 UTC, gogo1414 reviewed
고생했어~~ 훑어보면서 수정할 부분 조금 체크해봤어

추가로 Repository에 메서드 정의 반환값에 `Optional<>` 이 들어가지 않았는데 NPE가 발생하지 않을까?? 한번 생각나서 적어봤으~~~~

2024-10-14 01:58 UTC, gogo1414 commented on src/main/java/cholog/supp/api/comment/service/CommentService.java
>      }
분리👍👍

2024-10-14 01:58 UTC, gogo1414 commented on src/main/java/cholog/supp/api/member/service/MemberService.java
>  }
```suggestion
    }
}
```
공백 들어갔다!

2024-10-14 01:58 UTC, gogo1414 commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +            member);
```suggestion
        List<EachComment> comments = makeComments(
            post.getStudy().getId(),
            commentRepository.findAllByPostId(postId),
            member
        );
```
이렇게 아예 매개변수를 아래로 내리는게 더 보기 좋은거 같은데 어떤가요??

2024-10-14 01:58 UTC, gogo1414 commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +    private List<EachComment> makeComments(Long studyId, List<Comment> comments, Member member) {
```suggestion
    private List<EachComment> getComments(Long studyId, List<Comment> comments, Member member) {
```
`makeComments`라는 메서드명은 의견을 생성하는것으로 보이니 가져온다는 표현이 맞지 않을까??

2024-10-14 01:58 UTC, gogo1414 commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +            return new EachComment(comment, memberType, isMyComment);
여기 부분에서 `isMyComment`로 검증하는 부분과 해당 값을 `EachComment`에 같이 넣는 이유가 궁금한데 설명해줄 수 있어??

2024-10-14 01:58 UTC, gogo1414 commented on src/main/java/cholog/supp/common/config/JpaAuditingConfig.java
> +}
```suggestion
}

```
여기도 EOL(End Of Line) 놓쳤다!!

2024-10-14 06:47 UTC, boyekim commented on src/main/java/cholog/supp/api/post/controller/PostController.java
> +    @PostMapping("/post")
나는 사실 단건은 이후에 {postId} 로 구별이 되기때문에 굳이 복수의 의미로 s를 붙였을 때(posts) 보단 단수로 post 이렇게 놨을 때 더 잘 인식된다고 생각했고든?? 근데 그건 내가 그냥 API를 짠 사람이라 그런것 같구... 태현오빠와도 의견을 나눠봤을 때 다건은 posts로 명시하는게 다른사람이 읽기 편해보였어
근데 createPost는 하나의 게시글을 등록하는 것이기 때문에 자연스럽게 단수로 명시했어
복수로 명시하면 의미가 혼동되진 않을까??
하나의 질문글을 등록하는 시나리오에서도 복수 명시를 선호하는편이야??

2024-10-14 06:58 UTC, Choi-JJunho commented on src/main/java/cholog/supp/api/post/controller/PostController.java
> +    @PostMapping("/post")
URL로 자원을 나타내고, HTTP Method로 행위를 나타낸다고 생각해
posts (게시물들) 이라는 자원에 대한 행위를 취하는 것 이라고생각해서 posts라는 url 형태로 통일하는게 어떨까? 라는 생각이였어
그 안에 들어가는 세부 값들이 List인지 단건인지는 DTO로서 표현해도 좋다고 생각해
`게시물 여러건을 한번에 작성하는 API`라는 느낌으로 다가오지 않을까? 를 우려한것 같은데 위에서 말했듯 dto로 구분해야하지 않을까 싶어

안그러면 클라이언트에서 어디에서는 /posts를 사용하고 어디에서는 /post를 사용하고 선언하는데 복잡하다고 느낄 것 같아. 한마디로 휴먼에러를 높여서 관리 비용이 높아지지 않을까? 라는 우려도 있고

2024-10-14 07:25 UTC, boyekim commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +            member);
오 훨씬 보기 좋다

2024-10-14 07:26 UTC, boyekim commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +    private List<EachComment> makeComments(Long studyId, List<Comment> comments, Member member) {
그러네!!!!!!!

2024-10-14 07:30 UTC, boyekim commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +            return new EachComment(comment, memberType, isMyComment);
우리가 수정하기 기능이 있자나?? 그 의견글을 로그인한 본인이 쓴 거라면 '수정하기' 버튼이 보여야하니까 저 값을 알려주면 좋을 거라고 생각했어!

2024-10-14 07:33 UTC, boyekim commented on src/main/java/cholog/supp/db/post/Post.java
> +    private LocalDateTime modifiedDate;
적용해봤어!

2024-10-14 07:37 UTC, boyekim commented on src/main/java/cholog/supp/api/post/controller/PostController.java
> +    @PostMapping("/post")
아~~~
역할의 관점에서 보면 지금은 굳이굳이 url로도 한번 더 분리를 해버리는게 되는구나
어차피 dto로도 명시가 되니 url은 통일을하는게 오히려 리소스를 줄일 수 있겠다
하나 배워가 꼬마워 반영할게!!!

2024-10-14 08:02 UTC, boyekim commented
> 고생했어~~ 훑어보면서 수정할 부분 조금 체크해봤어
> 
> 추가로 Repository에 메서드 정의 반환값에 `Optional<>` 이 들어가지 않았는데 NPE가 발생하지 않을까?? 한번 생각나서 적어봤으~~~~

@gogo1414 
List 를 반환값으로 주는 메서드들에 말하는 거 맞을까??
List는 애초에 null을 반환하지 않으니 Optional로 묶는건 아무 소용이 없을 것 같아!
List를 반환받고 empty인지 검증하는 로직이 필요하겠다
이걸 추가해볼게!

2024-10-14 08:15 UTC, gogo1414 commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +    private List<EachComment> makeComments(Long studyId, List<Comment> comments, Member member) {
`List`도 좋은데 내 생각으로는 `Comments` 자체가 복수형이라 없어도 괜찮을거 같어

2024-10-14 08:16 UTC, gogo1414 commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +            return new EachComment(comment, memberType, isMyComment);
서비스 흐름상 바로바로 보이는게 좋으니까 있으면 편하겠다 대박이네👍👍

2024-10-14 09:02 UTC, boyekim commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +    private List<EachComment> makeComments(Long studyId, List<Comment> comments, Member member) {
List랑 관련 없는 것들에 보통 복수형으로 써와서(List를 전혀 받지 않는 request DTO의 이름을 복수형으로 명시한다던지) 반환값이 List 인것은 붙여주고자했어!!
어띃게생각해?? 그래서 난 이거는 List를 붙여주는게 좋을거라구 생각했어

2024-10-14 09:07 UTC, gogo1414 commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +    private List<EachComment> makeComments(Long studyId, List<Comment> comments, Member member) {
수민이 너가 네이밍한 방식이 따로 존재하면 그 틀을 유지하면 좋을거 같아👍👍👍

2024-10-14 09:53 UTC, Choi-JJunho approved these changes
굿굿 코멘트 몇개 확인 부탁할게

2024-10-14 09:53 UTC, Choi-JJunho commented on src/main/java/cholog/supp/api/post/controller/PostController.java
> +        return ResponseEntity.created(new URI("/api/v1/post/" + postId)).build();
Url에 posts! 글자 누락됐다

2024-10-14 09:53 UTC, Choi-JJunho commented on src/main/java/cholog/supp/api/post/dto/response/EachComment.java
> +    boolean isMyComment
isMySomething 뭔가 긴거같은데..
좀더 간결하게 표현할수있는 변수명은 없을까?

isOwner, isAuthor 등

2024-10-14 09:53 UTC, Choi-JJunho commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +            String memberType = memberStudyMap.getMemberCategory().getMemberType().toString();
toString을 재정의하거나 컨벤션이 정해지지 않은 상황에서 어떤값이 나올지 계속 의문을 가지게 되는거같아

name()을 반환하고싶은걸까?


참고글: https://velog.io/@skyepodium/%EC%9E%90%EB%B0%94-toString-%EC%9D%84-%ED%95%AD%EC%83%81-%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%9D%BC

2024-10-14 09:53 UTC, Choi-JJunho commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +    private List<EachComment> getCommentList(Long studyId, List<Comment> comments, Member member) {
엔티티값이 수정되지않는 조회쿼리라면 불필요한 트랜잭션이 열리지않게 readOnly 속성을 달아주면 좋을것 같아

참고글 https://velog.io/@junho5336/Transactional%EC%9D%98-readOnly%EC%97%90-%EB%8C%80%ED%95%B4

2024-10-14 10:33 UTC, boyekim commented on src/main/java/cholog/supp/api/post/dto/response/EachComment.java
> +    boolean isMyComment
isAuthor로 반영했어!!

2024-10-14 10:35 UTC, boyekim commented on src/main/java/cholog/supp/api/post/service/PostService.java
> +            String memberType = memberStudyMap.getMemberCategory().getMemberType().toString();
헐 name을 반환하려는게 맞아
바로 수정할게!

2024-10-14 12:12 UTC, merged