[feat] 로그인 기능을 구현한다.
cholog-project/supp pull request #4
Opened 2024-10-08 09:01 UTC by boyekim

### 궁금한점
명세서 상 로그인 성공 response가
{
  "message": "로그인 성공",
  "status" : 201,
  "data": { 
    "memberId" : 1
  }
}
으로 명세되어 있는데...
DB에 저장된 멤버아이디(PK)를 가져와서 담아주는건가용?!

2024-10-08 13:40 UTC, whxogus215 reviewed
코드 작성 스타일이 나랑 비슷한 것 같아서 읽기에 수월했어 😄 고생했으!

2024-10-08 13:40 UTC, whxogus215 commented on src/main/java/cholog/supp/api/common/SuccessMessage.java
> +    GET_POSTS_SUCCESS("질문 목록 조회 성공", HttpStatus.OK.value()),
`동사_목적어_성공`이라는 구조가 코드와 메시지를 잘 연결시키는 것 같아 👍
읽기에도 편한 것 같고! 작명 패턴은 직접 생각해본거야? 아니면 다른 코드를 참고해서 쓴거야?

2024-10-08 13:40 UTC, whxogus215 commented on src/main/java/cholog/supp/api/common/SuccessMessage.java
> +    GET_POST_SUCCESS("단일 질문 조회 성공", HttpStatus.OK.value()),
앞부분 동사가 HTTP 메서드인 `GET, POST, DELETE`에서 따온건줄 알았는데 `POST`가 게시글의 의미로 쓰인 것 같네.
나는 쓰기가 `WRITE`라면, 읽기를 `READ`라고 표현하는 편인데 수민이가 생각했을 때는 어떤 것 같아?

2024-10-08 13:40 UTC, whxogus215 commented on src/main/java/cholog/supp/api/member/controller/MemberController.java
> +
다른 메서드들과 달리 이 메서드의 시작 부분만 줄바꿈이 되어 있어!

2024-10-08 13:40 UTC, whxogus215 commented on src/main/java/cholog/supp/api/member/dto/response/SigninResponse.java
> +public class SigninResponse {
`request`의 `dto`는 Record 타입으로 생성했는데, `response`의 `dto`는 Record로 선언하지 않은 이유가 궁금해!

2024-10-08 13:40 UTC, whxogus215 commented on src/main/java/cholog/supp/common/auth/JWTUtils.java
> +            .claim("email",member.getEmail())
`,` 다음에 띄어쓰기가 필요할 것 같아

2024-10-08 14:08 UTC, boyekim commented on src/main/java/cholog/supp/api/common/SuccessMessage.java
> +    GET_POSTS_SUCCESS("질문 목록 조회 성공", HttpStatus.OK.value()),
예전에 접했던 방식인데 나도 너무 읽기 편하다 생각해서 그대로 쓰고있엉 ㅎㅎ

2024-10-08 14:13 UTC, boyekim commented on src/main/java/cholog/supp/api/common/SuccessMessage.java
> +    GET_POST_SUCCESS("단일 질문 조회 성공", HttpStatus.OK.value()),
읽기를 READ라고 해서 HTTP 메서드처럼 보이지 않게 하는게 나을 것 같다
괜히 혼동이 생기네 반영할게~!

2024-10-08 14:15 UTC, boyekim commented on src/main/java/cholog/supp/api/member/controller/MemberController.java
> +
헐 그러네 고마워

2024-10-08 14:33 UTC, boyekim commented on src/main/java/cholog/supp/api/member/dto/response/SigninResponse.java
> +public class SigninResponse {
사실 이 DTO가 아직쓰이지 않아..! 내가 본문에 써 놓은 궁금한점과 연관이 있는데, cookie에 직접 세팅하고 HttpServletResponse에 직접 담아서 주면 위의 본문에 명시된 memberId 전달이 굳이 필요없을것같았어(토큰 내에서도 `.setSubject(member.getId().toString())` 이렇게 한번 담겨지는데 꼭 필요할까? 하는 의문이 있었음)
그래서 형식을 크게 신경쓰지 않았었긴해
다음부터 response구성할 떄에는 record로 짜봐야겠다

2024-10-08 14:34 UTC, boyekim commented on src/main/java/cholog/supp/common/auth/JWTUtils.java
> +            .claim("email",member.getEmail())
뭐야 줄 정렬 분명 했는데....!🥹🥹🥹🥹🥹 바로 다시 할게

2024-10-08 15:15 UTC, whxogus215 commented on src/main/java/cholog/supp/api/member/dto/response/SigninResponse.java
> +public class SigninResponse {
그렇구나 로그인과 관련된 응답인만큼 쿠키에 담아서 전달하는 것만으로도 충분할 수도 있겠네.
게시글이나 댓글과 같은 경우라면 `data`에 `id`가 담기는게 맞는 것 같아.

2024-10-08 15:17 UTC, Choi-JJunho requested changes
헐 리뷰해놓고 마무리를 안했네
고생했어~!!

2024-10-08 15:17 UTC, Choi-JJunho commented on src/main/java/cholog/supp/api/common/APISuccessResponse.java
> +    T date
data인데 오타난거같네요~

2024-10-08 15:17 UTC, Choi-JJunho commented on src/main/java/cholog/supp/api/member/controller/MemberController.java
> +        response.addCookie(cookie);
쿠키에 jwt 토큰을 담아서 보내주는군요!

세션으로 구현할거라면 굳이 jwt를 사용하지 않아도 될거같아요 :) 

사용자의 아이디를 기반으로 한 임의의 문자열을 만들어서 세션으로 담아두기만해도 될거같아요!

참고자료: https://spring.io/projects/spring-session/

2024-10-08 15:17 UTC, Choi-JJunho commented on src/main/java/cholog/supp/api/member/dto/response/SigninResponse.java
> +}
Request에서는 record를 사용했는데 여기서는 record를 쓰지 않은 이유가 있을까요?

2024-10-08 15:17 UTC, Choi-JJunho commented on src/main/java/cholog/supp/api/member/service/MemberService.java
> +        return jwtUtils.createToken(member);
위에서 말했듯이 꼭 jwt여야할 이유가 있을까요? 세션을 활용하눈 방법을 확인해보죠 :)

2024-10-08 15:17 UTC, Choi-JJunho commented on src/main/java/cholog/supp/common/LoginMemberArgumentResolver.java
> +public class LoginMemberArgumentResolver implements HandlerMethodArgumentResolver {
이 Resolver는 아무 역할도 수행하지 않는것 같아요
선언한 이유가 있을까요?

2024-10-08 15:17 UTC, Choi-JJunho commented on src/main/java/cholog/supp/db/member/Member.java
> +}
Github 상에서 빨간 에러아이콘이 나오네요~
<img width="378" alt="image" src="https://github.com/user-attachments/assets/ae3aa426-a393-4180-a602-dd6090e90936">
POSIX 표준과 관련된 이야기인데 아래 글을 한번 읽어보시는걸 추천드려요~

참고 글: https://velog.io/@junho5336/No-newline-at-end-of-file

2024-10-08 15:17 UTC, Choi-JJunho commented on src/test/java/cholog/supp/JWTTest.java
> +    }
무엇을 테스트하는 내용일까요?
+) 불필요한 주석은 제거하는게 어떨까요?

2024-10-08 15:17 UTC, Choi-JJunho commented on src/main/java/cholog/supp/db/member/Member.java
> +    }
Lombok에는 NoArgConstructor라는 어노테이션이 있어요~

2024-10-08 15:21 UTC, boyekim commented on src/main/java/cholog/supp/api/common/APISuccessResponse.java
> +    T date
제 시력이 -0.5인가봅니다...

2024-10-08 15:28 UTC, boyekim commented on src/main/java/cholog/supp/api/member/dto/response/SigninResponse.java
> +}
위에도 똑같은거 답변 남겼는데 가져오자면
⬇️⬇️⬇️
사실 이 DTO가 아직쓰이지 않아..! 내가 본문에 써 놓은 궁금한점과 연관이 있는데, cookie에 직접 세팅하고 HttpServletResponse에 직접 담아서 주면 위의 본문에 명시된 memberId 전달이 굳이 필요없을것같았어(토큰 내에서도 .setSubject(member.getId().toString()) 이렇게 한번 담겨지는데 꼭 필요할까? 하는 의문이 있었음)
그래서 회의때 협의하고 사용여부를 결정할거였어서 형식을 크게 신경쓰지 않았었긴해
다음부터 response구성할 떄에는 record로 짜봐야겠다

그리고 방금 삭제하기로 협의헀어

2024-10-08 15:37 UTC, boyekim commented on src/main/java/cholog/supp/common/LoginMemberArgumentResolver.java
> +public class LoginMemberArgumentResolver implements HandlerMethodArgumentResolver {
컨트롤러 실행 이전에 토큰을 인증하고 사용자정보를 반환할 상황이 필요할 것 같아서 선언을 미리 해뒀었어요

2024-10-08 15:40 UTC, boyekim commented on src/main/java/cholog/supp/db/member/Member.java
> +}
항상 신경쓰던 부분이었는데 JPA buddy가 해 준 부분은 신경안썼나봐요ㅜ 앞으로 꼭 신경쓰겠습니다 🥹

2024-10-08 15:45 UTC, boyekim commented on src/test/java/cholog/supp/JWTTest.java
> +    }
`@Value`로 secretKey를 가져올 때 null로 예외가 터지는지(환경변수 인식이 잘 되는지) 빠르게 확인하고자 간단하게 만들었습니다. 확인은 하고 싶은데 그렇다고 이 테스트를 위해 secretKey를 get하는 메서드를 만들기 싫었어요...
다른 사람이 보았을 때에는 어떤 테스트인지 인식하기 힘들 것 같긴합니다ㅜ

2024-10-08 15:46 UTC, boyekim commented on src/main/java/cholog/supp/db/member/Member.java
> +    }
악!!!!!! 반영했습니다 이것도 어제 밤에 졸린채로 코딩해서 ㅜㅜㅜㅜ~~~~오늘 꼭 고칠라했는데!!! 까먹었어요!!!ㅜㅜㅜ😭😭😭

2024-10-09 05:42 UTC, Choi-JJunho approved these changes
페어 작업하면서 확인했습니다 :)

2024-10-09 05:43 UTC, merged